### ISSUE TITLE
SQL fail on double author

### ISSUE THREAD

**Issue by campZero** [eFiction/v5_installer#1]
In case the admin of an eFi3 has changed the name of an author and now this name exists twice, it will lead to a crash on the installer.

`SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '*******' for key 'name1' [/var/www/clients/client0/web22/dev/install/lib/db/sql.php:227]

[install/lib/db/sql.php:227] PDOStatement->execute()
[install/lib/db/sql/mapper.php:421] DB\SQL->exec()
[install/lib/db/cursor.php:242] DB\SQL\Mapper->insert()
[install/inc/sql/upgrade_3_5_x/job_users.php:101] DB\Cursor->save()
[install/inc/upgradetools.php:607] users_copy()
[install/inc/upgradetools.php:333] jobStart()
[install/inc/upgrade.php:124] upgradetools::processJobs()
[install/lib/base.php:1776] upgrade->steps()
[install/lib/base.php:1599] Base->call()
[install/index.php:58] Base->run()`

**Comment by marciesdr** [comment]
I had this happen when two authors had the same name during the upgrade, but I just changed the second one to something else and it went through after that.

**Comment by campZero** [comment]
Yeah that's bad, at least now it will tell you before wasting time on lots of steps
