### ISSUE TITLE
Error on "Create usermenu entries"

### ISSUE THREAD

**Issue by holls91** [eFiction/v5_installer#2]
While running the new version of the installer, I encountered an exception on "Page menus" step, at "#2 Create usermenu entries".

I did a bit of debugging and found the bug: a comma is missing in inc\sql\install\job_menu.php, at the end of line 124 ("('Authoring_Deleted%%0', 5, 'author/uid=%ID%/deleted', '{ICON:following} {ICON:trash}', 'author_sub', 1, NULL)").

Putting the comma solved the problem!

**Comment by campZero** [comment]
That happens when I add lines afterwards and don't give it a test-drive, free facepalms available.
