### ISSUE TITLE
Error on "job_various.php"

### ISSUE THREAD

**Issue by holls91** [eFiction/v5_installer#3]
While running the installer, I got an exception on file inc\sql\install\job_various.php, at line 16.

Currently, the code is:

`$fw->jobSteps += array(
		"shoutbox"	=> "Copy shoutbox data"
		"db_keys"	=> "Create foreign keys relations",
);
`

but I think it should be

`$fw->jobSteps += array(
		"shoutbox"	=> "Copy shoutbox data",
		"db_keys"	=> "Create foreign keys relations"
);
`

**Comment by campZero** [comment]
Well, see #2 for facepalm.
Thanks for reporting
