### ISSUE TITLE
New Install - ratings

### ISSUE THREAD

**Issue by marciesdr** [eFiction/v5_installer#4]
did a new install and seen when it comes to adding a story you couldn't insert ratings. Instead you had to insert them via php admin and insert row. 

Was easy enough to add them myself but for newbies it might be a problem. 

Also new stories tab did not update and Archive stats did not count chapters. No word count either.
Not sure why dates look like this: 31.12.1969 18:00

Feedback in UserCP

Illegal string offset 'ST'

[fiction/app/model/usercp.php:447] Base->{closure}()
[fiction/app/controller/usercp.php:436] Model\UserCP->feedbackHomeStats()
[fiction/app/controller/usercp.php:315] Controller\UserCP->feedbackHome()
[fiction/app/controller/usercp.php:34] Controller\UserCP->feedback()
[fiction/index.php:117] Base->run()

This is pretty much everything i seen with a new install. There's a few error in the Admin CP but I know that's still under development. Just though I would post to let you know.

My test archive is here: 
https://simplymitchellkummen.com/fiction/

**Comment by campZero** [comment]
Okay, that's not actually an issue with the installer, so I marked it invalid.

I will look up the errors and add them under the eFiction issues if need be.

Date is easy to explain, it get's set to 01.01.1970 00:00, and then gets adjusted to your timezone, could it be that you are located in GMT+0 ?
I know updates don't properly count in all occasions, I am on the issue and am slowly adding routines and triggers there.

**Comment by marciesdr** [comment]
Just to clarify this is the published date on a story.

**Comment by campZero** [comment]
Date handling was a mess, especiall coming from the user panel. That should be cleared up now, other issues are pending, but this is not the right ticket for them.
