### ISSUE TITLE
The (unset) cast is deprecated

### ISSUE THREAD

**Issue by HarikYT** [eFiction/v5_installer#5]
I can't install this.

[D:/Website/htdocs/eFictionV5/lib/base.php:2152] Base->error()
[D:/Website/htdocs/eFictionV5/lib/base.php:2016] Base->{closure}()
[D:/Website/htdocs/eFictionV5/lib/base.php:2016] require()
[D:/Website/htdocs/eFictionV5/inc/configtools.php:100] spl_autoload_call()
[D:/Website/htdocs/eFictionV5/inc/install.php:112] configtools::testConfig()
[D:/Website/htdocs/eFictionV5/lib/base.php:1776] install->saveConfig()
[D:/Website/htdocs/eFictionV5/lib/base.php:1599] Base->call()
[D:/Website/htdocs/eFictionV5/index.php:61] Base->run()

Please help.

**Comment by campZero** [comment]
Updated the framework lib to version 3.6.5, should fix this

**Comment by HarikYT** [comment]
Doesn't work? why though?

**Comment by HarikYT** [comment]
Wait. Deleting and Reinstalling seemed to work :)
Thx
